FROM node:22-alpine3.21

WORKDIR /app

RUN apk add --no-cache openssl

COPY package*.json ./

RUN npm install

COPY . ./

RUN npx prisma generate

ENV NODE_ENV=development
ENV DATABASE_URL=mongodb://mongo:27017/op

CMD ["npm", "run", "dev"]
